version: '3.8'

services:
  app:
    build: .
    ports:
      - "6001:6001"
    environment:
      DATABASE_URL: postgres://nitish:nl9GNah3DHtBCl5BAdXjLaSxcbnPp25q@dpg-cn91g28l5elc73909mh0-a/bitespeed_fj5u
    depends_on:
      - db
    networks:
      - my-network

  
