version: '3.8'

services:
  app:
    build: .
    ports:
      - "6001:6001"
    environment:
      DATABASE_URL: postgresql://nitish:1234@db:5432/bitespeed
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bitespeed
      POSTGRES_USER: nitish
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network

volumes:
  my_postgres_data:

networks:
  my-network:
